export const clubConfig = {
  name: 'Dynamic Leaders Forum Toastmasters Club',
  clubNumber: '07756864',
  area: '1',
  division: 'H',
  district: '229',
  timezoneLabel: 'IST · GMT +5:30',
  logoUrl: '/toastmasters-logo.png',
  qrCodeUrl: '/qr-placeholder.svg',
  url: 'https://linktr.ee/dlftmc',
  footerText: 'To know more about club activities, visit',
  colors: {
    loyalBlue: '#004165',
    blissfulBlue: '#006094',
    trueMaroon: '#772432',
    deepMaroon: '#3b0104',
    richMaroon: '#781327',
    coolGray: '#a9b2b1',
    happyYellow: '#f2df74',
    fairGray: '#f5f5f5',
  },
  executiveCommittee: [
    { position: 'Club President', name: 'TM Janaki K B' },
    { position: 'Vice President Education', name: 'TM Amir' },
    { position: 'Vice President Membership', name: 'TM Felix' },
    { position: 'Vice President Public Relations', name: 'TM Manjumatha' },
    { position: 'Club Secretary', name: 'TM Avanthika' },
    { position: 'Club Treasurer', name: 'TM Savitha' },
    { position: 'Sergeant at Arms', name: 'TM Radhika' },
    { position: 'Immediate Past President', name: 'TM Tathagatha' },
  ],
}

export const roleDefinitions = [
  { key: 'presidingOfficer', label: 'Presiding Officer', required: true },
  { key: 'sergeantAtArms', label: 'Sergeant at Arms', required: true },
  { key: 'toastmaster', label: 'Toastmaster of the Day', required: true },
  { key: 'generalEvaluator', label: 'General Evaluator', required: true },
  { key: 'timer', label: 'Timer', required: true },
  { key: 'ahCounter', label: 'Ah-Counter', required: true },
  { key: 'grammarian', label: 'Grammarian / Idiom Master', required: true },
  { key: 'listeningMaster', label: 'Listening Master', required: true },
  { key: 'tableTopicsMaster', label: 'Table Topics Master', required: true },
]
